import type { Metadata } from "next";
import { Providers } from "./providers"; // 👈 اینجا ایمپورتش کن
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "فروش یار",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" data-theme='dark'   >
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         <Providers> 
        {children}
        </Providers>
      </body>
    </html>
  );
}
